---
- name: Create Jenkins user
  user:
    name: jenkins
    shell: /bin/bash
    state: present

- name: Ensure SSH directory exists
  file:
    path: /home/jenkins/.ssh
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0700'

- name: Copy public key for SSH access (Jenkins master -> slave)
  copy:
    src: jenkins-key.pub
    dest: /home/jenkins/.ssh/authorized_keys
    owner: jenkins
    group: jenkins
    mode: '0600'

- name: Allow jenkins user to use Docker
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: true
